
from .customerror import CustomError


class InputException(CustomError): 
    pass